version: '3'

services:
  nginx:
    image: nginx:1.14-alpine
    ports:
    - 80:80
    volumes:
    - ./:/app
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./docker/nginx/mime.type:/etc/nginx/mime.type
    - ./docker/nginx/conf.d/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
    - php
    - mysqldb
#    networks:
#    - todo_default_network

  php:
    build: docker/php
    volumes:
    - ./:/app
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#    networks:
#    - todo_default_network

  mysqldb:
    image: mysql:5.7
    command: --init-file /tmp/mysql/todo.dump.sql
    volumes:
      - ./_db_mysql:/var/lib/mysql
      - ./docker/mysql/todo.dump.sql:/tmp/mysql/todo.dump.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
#    networks:
#    - todo_default_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    ports:
    - 8099:80
    volumes:
    - /sessions
    depends_on:
      - mysqldb
    environment:
    - PMA_VERBOSE=todo
    - PMA_PORT=3306
    - PMA_USER=root
    - PMA_PASSWORD=root
    - PMA_HOST=mysqldb
#	networks:
#	- todo_default_network
#networks:
#  todo_default_network:
#    driver: bridge
