<?php

namespace DoctrineProxies\__CG__\ToDo\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TodoList extends \ToDo\Entity\TodoList implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

        return parent::__get($name);
    }





    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'id', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'nameList', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'sessionId', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'complitStatus', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'status', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'user', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'items'];
        }

        return ['__isInitialized__', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'id', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'nameList', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'sessionId', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'complitStatus', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'status', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'user', '' . "\0" . 'ToDo\\Entity\\TodoList' . "\0" . 'items'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TodoList $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameList', []);

        return parent::getNameList();
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionId', []);

        return parent::getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function getComplitStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplitStatus', []);

        return parent::getComplitStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \ToDo\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsAsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsAsArray', []);

        return parent::getItemsAsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameList(string $nameList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameList', [$nameList]);

        return parent::setNameList($nameList);
    }

    /**
     * {@inheritDoc}
     */
    public function setSessionId(string $session)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessionId', [$session]);

        return parent::setSessionId($session);
    }

    /**
     * {@inheritDoc}
     */
    public function setCompliteStatus(int $compileStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompliteStatus', [$compileStatus]);

        return parent::setCompliteStatus($compileStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $satus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$satus]);

        return parent::setStatus($satus);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\ToDo\Entity\Users $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
